# Generated by Django 4.0.5 on 2022-07-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsoApp', '0003_alter_consolas_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribuidores',
            old_name='ingreso',
            new_name='stock',
        ),
    ]
